version: '3.8'

services:
  peba-finance-db:
    image: mysql:8.0
    container_name: peba-finance-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: abcv123
      MYSQL_DATABASE: peba_finance
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql-data: