services:
  peba-finance-db:
    image: mysql:8.0
    container_name: peba-finance-db
    restart: always
    env_file:
      - src/PebaFinance.Api/.env
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password

  peba-finance-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: peba-finance-api
    restart: always
    ports:
      - "5000:8080"
    depends_on:
      - peba-finance-db
    env_file:
      - src/PebaFinance.Api/.env

volumes:
  mysql-data:
